
[[keyboard.bindings]]
chars = '\p'
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = '\n'
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[general]
live_config_reload = true
import = ["./themes/google.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 7

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 14

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',â”‚`|:"' ()[]{}<>	'''

[window]
dynamic_padding = true
startup_mode = "Fullscreen"

[window.padding]
x = 1
y = 0

[keyboard]
